config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")

  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in, only: [:create, :new]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to cats_url
    else
      flash.now[:errors]= @user.errors.full_messages
      render :new
    end

  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/users/new.html.erb
<h1>Sign Up Form</h1>

<% flash[:errors].try(:each) do |error| %>
  <%=  error %>
<% end %>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username: </label>
  <input type="text" id="username" name="user[username]" value="">

  <br>

  <label for="password">Password:</label>
  <input type="text" id="password" name="user[password]" value="">

  <br>

  <input type="Submit" value="Sign Up">
</form>