config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")

  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCatsDay1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if logged_in? %>

      <p>HELLO </p> <%= current_user.username %>
      <form class="" action="<%= sessions_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" name="" value="SIGN OUT">
      </form>

    <% else %>

    <% flash[:errors].try(:each) do |error| %>
      <%=  error %>
    <% end %>

      <form action="<%= sessions_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <label for="username">Username: </label>
        <input type="text" id="username" name="user[username]" value="">

        <br>

        <label for="password">Password:</label>
        <input type="text" id="password" name="user[password]" value="">

        <br>

        <input type="Submit" value="LOG IN  ">
      </form>

    <% end %>
  </header>

<%= yield %>

</body>
</html>